### ISSUE TITLE
Missing fork icon when performing forking

### ISSUE THREAD

**Issue by wlawt** [MLH-Fellowship/babel-sandbox#102]
![image](https://user-images.githubusercontent.com/22751307/90063218-0a68fd00-dcb7-11ea-97b4-fb90994e6b46.png)

To reproduce, follow #93 logic

Problem from #100

**Comment by garrettluu** [comment]
Should be fixed by #103. I believe I forgot to commit the `ForkModal` component earlier so someone commented it out for testing purposes.
