### ISSUE TITLE
Babelconfig is not restored from server state

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#120]
1. Modify the babelconfig
2. Save the replstate
3. Reload the page
4. Babelconfig is empty

This could be a result of Ian's refactor #98

**Comment by garrettluu** [comment]
I can't seem to reproduce this bug from @penguingovernor 's branch. #125 seems to have fixed this issue.

**Comment by ianjennings** [comment]
Nice!
