### ISSUE TITLE
UI Chrome

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#19]
We need to improve the UI buttons, a toolbar would be way better.

See here:
https://babeljs.io/en/repl

I think starting with this kind of toolbar makes a lot of sense:

![2020-07-23 01_08_08-Menu - Semantic UI React](https://user-images.githubusercontent.com/318295/88256471-041bce00-cc81-11ea-81cb-dc6fc6a287d0.png)
https://react.semantic-ui.com/collections/menu/#types-attached

This is more likely page chrome. IE, this is the root layout.

## Deliverables:
- Wrap the page in the semantic-ui component above
- Apply babel colors from #20 if possible
- See babel repl for inspiration

**Comment by wlawt** [comment]
Close issue with #23 on merge
