### ISSUE TITLE
Show AST with code folding

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#2]
From sandboxes created by [ianjennings](https://github.com/ianjennings): babel/sandboxes#16  

- [ ] option to show AST with code folding/highlighting (ASTExplorer)
    - example: https://github.com/babel/website/pull/1933

Deliverables:
- Include AST code explor as an option for "output" (box 4 and 6 in diagram below)

![](https://media.discordapp.net/attachments/719561552067297366/735621400294981722/2020-07-22_17_09_53-Movies__TV.png?width=971&height=642)

**Comment by ianjennings** [comment]
Henry says:
```
henryToday at 2:02 PM
Ideally we could just hook into astexplorer since it does some of this already but I think that's a lot more work to understand and integrate

ianjenningsToday at 2:14 PM
oooo
[2:17 PM]
It looks like it's been prototyped as a panel in repl
[2:17 PM]
that's how I imagined it, was hoping we could include it as a react component

henryToday at 2:18 PM
Yeah that would be great too, it's all about react anyway
[2:18 PM]
I did ask Felix who made it about modularity
NEW
[2:18 PM]
Then we could just reuse things
```

**Comment by ianjennings** [comment]
See here
![image](https://user-images.githubusercontent.com/318295/88329492-aa062180-ccef-11ea-8bd6-9abcf7a98e27.png)

From this pull https://github.com/babel/website/pull/1933

**Comment by ianjennings** [comment]
The package is here:
https://astexplorer.net/

Readme here:
https://github.com/fkling/astexplorer/blob/master/README.md

This needs to be included for every output.

**Comment by ianjennings** [comment]
We should be able to steal some components from here:
https://github.com/fkling/astexplorer/tree/master/website/src/components

**Comment by ianjennings** [comment]
So this pull has all the files in it in the context of current repl:
https://github.com/babel/website/pull/1933/files?file-filters%5B%5D=.js

We want this functionality in our own REPL

This is the REPL as it is now:
https://github.com/babel/website/tree/master/js/repl

**Comment by ianjennings** [comment]
**TL:DR**: Essentially we want the `ASTPanel` from [here](https://github.com/babel/website/pull/1933) in this repo.

**Comment by barronwei** [comment]
> The package is here:
> https://astexplorer.net/
> 
> Readme here:
> https://github.com/fkling/astexplorer/blob/master/README.md
> 
> This needs to be included for every output.

What do you mean by this?

**Comment by ianjennings** [comment]
There can be multiple outputs, so the `AST` component may be rendered more than once. The new design allows for dynamically adding and removing configs / outputs.

**Comment by ianjennings** [comment]
Ok, I was pretty off on my original task. I just cloned the `astexploerer` and the repo is way more complex than what I suggested previously.

I think the call from here is to merge the astexplorer here:
https://github.com/fkling/astexplorer/blob/master/website/src/app.js

Here is an article on how to merge the two.
https://medium.com/@sumn2u/merging-different-isolated-react-apps-into-single-app-e2158d19868d

**Comment by barronwei** [comment]
> Ok, I was pretty off on my original task. I just cloned the `astexploerer` and the repo is way more complex than what I suggested previously.
> 
> I think the call from here is to merge the astexplorer here:
> https://github.com/fkling/astexplorer/blob/master/website/src/app.js
> 
> Here is an article on how to merge the two.
> https://medium.com/@sumn2u/merging-different-isolated-react-apps-into-single-app-e2158d19868d

This article appears to be merging two applications that do not have shared state. I am going to look for the AST Explorer components that we are necessary for our purposes.

**Comment by barronwei** [comment]
Looks like AST Explorer does not have a license, so I will be writing my own AST visualization!

**Comment by wlawt** [comment]
The [Babel parser docs](https://babeljs.io/docs/en/babel-parser) supports lots of plugins, however, we'll only need the ones that #52 from @garrettluu supports.
