### ISSUE TITLE
Get Babel brand assets

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#20]
The babel homepage and repl have a consistent color scheme. We need the source colors. 

We also need the babel logo and whatever color scheme the babel repel is configured to use.

Deliverables:
- collection of hex colors that represent the babel homepage
    - we need blacks and whites! very important!
    - bonus for border colors
- babel logo (png, highest resolution possible)
- color scheme for babel code editor (ex: monokai)
    - can probably be found with `view source`

**Comment by wlawt** [comment]
![image](https://user-images.githubusercontent.com/22751307/88326221-d0c65700-ccf3-11ea-9ea8-b3c8d886c967.png)


## Colors 
- (1) Header background: `#323330`
- (2) Font color (on hover): `#EAD053`
- (3) Side-navbar background: `#2C3138`

## Fonts
- (2 + 3) Segoe UI
- (4) Consolas
- (5) Monospace

**Comment by ianjennings** [comment]
I found the logo source here:
https://github.com/babel/logo

**Comment by ianjennings** [comment]
I think the code editor theme is "darcula"
https://codemirror.net/demo/theme.html#darcula

**Comment by ianjennings** [comment]
Babel Yellow: `#f5da55`

**Comment by mohammedsahl** [comment]
The [CSS](https://gist.github.com/mohammedsahl/a6d67bea76803bf85f1410a29c7eef4e)

**Comment by wlawt** [comment]
Sweet, this covers the basics of what we'll need!
