### ISSUE TITLE
The most awesome schema ever

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#26]
# State Encoding

Author: Jorge Henriquez (contact@jorgehenriquez.dev)

## Needs and Goal

Need: Uses need to be able to recreate a babel sandbox.

Goal: Allow users to recreate a babel sandbox.

Design Objective:

Design a system that takes in the current state of the sandbox (`source code`, `custom plugin`, and `config(s)`).
Then that state must be encoded in such a way that it can be compactly stored and extendable if the state parameters change in the future.
Once the state is encoded it must be able to be stored in some medium that is retrievable.

## Design

Since we need the babel sandbox state (`S`) to be extendable we can enforce a flexible schema like so:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "The root schema",
  "description": "The root schema comprises the entire JSON document.",
  "default": {},
  "required": [],
  "properties": {
    "source": {
      "$id": "#/properties/source",
      "type": "string",
      "title": "The source schema",
      "description": "The source code of the page.",
      "default": ""
    },
    "use_plugin": {
      "$id": "#/properties/use_plugin",
      "type": "boolean",
      "title": "The use_plugin schema",
      "description": "A flag to represent whether or not a custom plugin was used.",
      "default": false
    },
    "plugin_source": {
      "$id": "#/properties/plugin_source",
      "type": "string",
      "title": "The plugin_source schema",
      "description": "The plugin's source code.",
      "default": ""
    },
    "configs": {
      "$id": "#/properties/configs",
      "type": "array",
      "title": "The configs schema",
      "description": "An array of babel configurations.",
      "default": [],
      "additionalItems": false,
      "items": {
        "$id": "#/properties/configs/items",
        "anyOf": [
          {
            "$id": "#/properties/configs/items/anyOf/0",
            "type": "string",
            "title": "The first anyOf schema",
            "description": "A babel configuration.",
            "default": ""
          }
        ]
      }
    }
  },
  "additionalProperties": false
}
```

We can then serialize this state by calling `JSON.stringify` on it yielding the encoded state `S_e`.
And to be efficient with space we can `gzip` `S_e` to yield `S_ge`.
Now here is there some experimenting to be done:

1. URI Encode `S_ge` and pass this along to the user when they want to share their sandbox.
   The users of the link would then decompress `S_ge` to get `S_e` a call to `JSON.parse` would then yield `S` allowing the program to restore the user state

2. Maintain the gzipped state `S_ge` and store it in an external database.
   We would then hash this state `S_ge` to yield `H`.
   To avoid duplicates we check if `H` is already in the database.
   If it's not in the database a unique id generated for this state and stored along with `S_ge` and `H`.
   If `H` is in the database then we just retrieve `S_ge` and the unique identifier.

**Comment by ianjennings** [comment]
#9, #13, #6

**Comment by ianjennings** [comment]
Needs to support multiple plugins. See 3 and 5 below.

![image](https://user-images.githubusercontent.com/318295/88447407-9eeae880-cdf8-11ea-8481-1a856b0c19fd.png)

**Comment by penguingovernor** [comment]
The mockup seems to have:

1 source code area.
1 plugin code area.
n configs. 

So we'd want something like this right?

```json
{
   "sourceCode": "foo",
   "pluginCode": "bar",
   "configs": [
      "baz",
      "qux"
   ]
}
```

**Comment by ianjennings** [comment]
Yeah I think this looks good

**Comment by penguingovernor** [comment]
One JSON schema nice and hot for everyone 🥞: 

```json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "http://example.com/example.json",
	"type": "object",
	"title": "The root schema",
	"description": "The root schema comprises the entire JSON document.",
	"default": {},
	"required": [],
	"properties": {
		"source": {
			"$id": "#/properties/source",
			"type": "string",
			"title": "The source schema",
			"description": "The source code of the page.",
			"default": ""
		},
		"plugin_source": {
			"$id": "#/properties/plugin_source",
			"type": "string",
			"title": "The plugin_source schema",
			"description": "The plugin's source code.",
			"default": ""
		},
		"configs": {
			"$id": "#/properties/configs",
			"type": "array",
			"title": "The configs schema",
			"description": "An array of babel configurations.",
			"default": [],
			"additionalItems": false,
			"items": {
				"$id": "#/properties/configs/items",
				"anyOf": [{
					"$id": "#/properties/configs/items/anyOf/0",
					"type": "string",
					"title": "The first anyOf schema",
					"description": "A babel configuration.",
					"default": ""
				}]
			}
		}
	},
	"additionalProperties": false
}
```

**Comment by ianjennings** [comment]
So according to our customer, there are now multiple everything.

![image](https://user-images.githubusercontent.com/318295/88700256-08efe000-d0ce-11ea-8eb4-5083c87aaebc.png)

**Comment by wlawt** [comment]
I also described how we're going to integrate this into the API via #25
