### ISSUE TITLE
Add ability to fork a saved config

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#27]
Add a property "forks", and "forkedFrom" to configs in the db.

Make a new API route.

```
POST /fork/:id
```

When someone hits this route.

Get the config with `id`, let's call this `source`.

Create a new config with:

```
forkedFrom: source.id
config: source.config
```

Then update `source` and append the id of the new row to `forks`.

**Comment by wlawt** [comment]
### Task: Add ability to fork a saved config
1. Create a Controller `ForkController` that'll handle the POST
2. Using the `Config` model, we want to use `.findOne()` or similar to find the entry that matches the id
3. `.create()` new entry to the `Config` model 
    - Update `ForkedFrom` with the id (from `/fork/:id`)
4. Append the id created in step 3 to the `forks` source

**The expected output:**
- A cloned copy of the source config with the addition of `forkFrom: id` being updated
- The source config should have an updated list of `forks` with the id from the cloned copy
