### ISSUE TITLE
Render fork information in UI

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#28]
See #27

Should include:

- link to parent
- the # of forks
- possibility to list forks

**Comment by ianjennings** [comment]
https://react.semantic-ui.com/elements/button/#types-labeled

![image](https://user-images.githubusercontent.com/318295/89448351-1c79f700-d71d-11ea-963e-089dfe2b8c0f.png)

**Comment by ianjennings** [comment]
Link up with @mohammedsahl to understand where this info will come from.

**Comment by mohammedsahl** [comment]
Only the `forkedFrom` and `forks` fields are relevant here, all others are to be ignored

### The `res` from a newly created fork (POST) will look like `/api/v1/blobs/fork/:id`
```json
{
  "createdAt": 1596651998648,
  "updatedAt": 1596651998648,
  "forkedFrom": "hkgsf9de2d55e05e987cc5235",
  "forks":[],
  "id": "5f2af9de2d55e05e987cc5e9",
  "url": "/share/5f2af9de2d55e05e987cc5e9"
}
```
### The `res` from (GET)ting a blob that has forks will look like `/api/v1/blobs/get-blob/:id`
```json
{
  "createdAt": 1596651998648,
  "updatedAt": 1596651998648,
  "source" : "d6sffg6sd98f9fgs96d",
  "plugin" : "9s8d7f6fg9sd87f6sg",
  "configs" : ["9asdf789fg6sdffg6", "a897sdf6asdf696asdf"],
  "forkedFrom": "",
  "forks":["hkgsf9de2d55e05e987cc5235", "5f2af9de2d55e05e987cc5e9"],
  "id": "5f2af9de2d55e05e987cc5e9",
  "url": "/share/5f2af9de2d55e05e987cc5e9"
  
}
```
### The `res` from (GET)ing a fork of a fork  `/api/v1/blobs/get-blob/:id`
```json
{
  "createdAt": 1596651998648,
  "updatedAt": 1596651998648,
  "source" : "d6sffg6sd98f9fgs96d",
  "plugin" : "9s8d7f6fg9sd87f6sg",
  "configs" : ["9asdf789fg6sdffg6", "a897sdf6asdf696asdf"],
  "forkedFrom": "askdfas8d7fasd67a9g67",
  "forks":["hkgsf9de2d55e05e987cc5235", "5f2af9de2d55e05e987cc5e9"],
  "id": "5f2af9de2d55e05e987cc5e9",
  "url": "/share/5f2af9de2d55e05e987cc5e9"
}
```

**Comment by garrettluu** [comment]
> The `res` from a newly created fork (POST) will look like `/api/v1/blobs/fork/:id`

Where would the `id` parameter that I need to pass in come from? I think we should just have POST  `/api/v1/blobs/fork` and the back-end should auto-generate the `id` or pull it from somewhere else, since front-end doesn't keep track of `id` anywhere.

**Comment by mohammedsahl** [comment]
The `id` is just the blob being forked
Have a look at #27. Blob is referred to as config in that issue
