### ISSUE TITLE
How do we store code on the server?

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#29]
The server will need to store babel configs and sample JS. How do we store it?

**Comment by ianjennings** [comment]
Server will hash the code to store in db. Client will just send code server.

- maxLimit
- will take up to max
- hash into base64 url

**Comment by ianjennings** [comment]
Base64 hash of the js source. 
Key is URL, value will be sourcecode.

Key is some unique id for the sandbox.

**Comment by ianjennings** [comment]
Related to #13 and #9

**Comment by mohammedsahl** [comment]
Can we update the original schema in #26 just to formalize the spec?
