### ISSUE TITLE
Import plugins

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#5]
From sandboxes created by [ianjennings](https://github.com/ianjennings): babel/sandboxes#13  

Should be able to import plugin into the codesandbox from the babel source / source code repo.

**Comment by ianjennings** [comment]
The Babel REPL does this already, but it's not great.

**Comment by ianjennings** [comment]
Babel REPL
https://babeljs.io/docs/en/plugins/#plugin-options

```js
{
  "plugins": [
    [
      "transform-async-to-module-method",
      {
        "module": "bluebird",
        "method": "coroutine"
      }
    ]
  ]
}
```

**Comment by ianjennings** [comment]
![2020-07-27 14_33_04-](https://user-images.githubusercontent.com/318295/88583641-1ea1ce80-d016-11ea-9cfd-72634eac5733.png)

**Comment by ianjennings** [comment]
Upon looking at the source, it seems like Henry does not intend to include *every* babel plugin like the above.

If you look here, it seems like a predefined list of plugins is ok.
https://github.com/MLH-Fellowship/babel-sandbox/blob/master/src/plugins-list.js

```js
export const plugins = {};
export const presets = {};

// If you want to add custom plugins or presets, you can register them
// at plugins-list.js in dependencies

plugins[
  "@babel/plugin-external-helpers"
] = require("@babel/plugin-external-helpers");
plugins[
  "babel-plugin-polyfill-corejs2"
] = require("babel-plugin-polyfill-corejs2");
plugins[
  "babel-plugin-polyfill-corejs3"
] = require("babel-plugin-polyfill-corejs3");
plugins[
  "babel-plugin-polyfill-es-shims"
] = require("babel-plugin-polyfill-es-shims");
plugins[
  "babel-plugin-polyfill-regenerator"
] = require("babel-plugin-polyfill-regenerator");

presets["@babel/preset-env"] = require("@babel/preset-env");
presets["@babel/preset-react"] = require("@babel/preset-react");
```

**Comment by garrettluu** [comment]
So how exactly should we structure this? Are we going to have a predefined list for the user to pick from? How would adding new plugins work?

**Comment by wlawt** [comment]
@garrettluu for now, I think we should stick to a predefined list. 

Maybe we can add dynamic plugin list in the future?

**Comment by ianjennings** [comment]
@wlawt on the same page. I don't think we want to bundle the plugins like this by default either.

@garrettluu and I also talked about including a default plugin config, something the current REPL doesn't do. So we have this new proposal:

```js
[{
    name: 'babel-plugin-polyfill-regenerator,
    description: 'does this or that',
    fileLocation: '/plugins/babel-plugin-polyfill.js',
    config: {}
}]
```

**Comment by ianjennings** [comment]
@garrettluu asked a few questions today:

# How do we include a plugin?

Featured plugins will exist within a directory called `/plugins`. 

We will have an internal JSON document that contains that list of plugins. This will help us render them on the front end.

```js
[{
    name: 'babel-plugin-polyfill-regenerator,
    description: 'does this or that',
    fileLocation: './static/plugins/example.js',
    defaultConfig:  {
        "module": "bluebird",
        "method": "coroutine"
      }
}]
```

Then, when a plugin is selected, `fileLocation` and `defaultConfig` are used to build the babel config like so:

```js
babelConfig.plugins.push([fileLocation, defaultConfig])
```

Which will evaluate to:

```js
{
  "plugins": [
    [
     './static/plugins/example.js',
      {
        "module": "bluebird",
        "method": "coroutine"
      }
    ]
  ]
}
```

Then the application is reloaded and the plugin should be activated within our babel instance. 

# How do we incorporate presets?

The syntax for presets looks identical. The logic above may be able to be reused to load presets. IE, an additional /presets folder, etc.

```js
{
  "presets": [
    ["@babel/preset-env", {
      "loose": true,
      "modules": false
    }]
  ]
}
```

**Comment by ianjennings** [comment]
Here's an example of using babel-standalone to load the plugin via bundle.run.
https://jsfiddle.net/386wfcmv/12/

Bundle.run compiles the plugin with support for browsers through the `window` object. Therefore dynamically loaded plugins are available through `window.babelPluginCamelCase`.

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.26.0/babel.min.js" integrity="sha512-kp7YHLxuJDJcOzStgd6vtpxr4ZU9kjn77e6dBsivSz+pUuAuMlE2UTdKB7jjsWT84qbS8kdCWHPETnP/ctrFsA==" crossorigin="anonymous"></script>
<script src="https://bundle.run/babel-plugin-minify-mangle-names@0.5.0"></script>
```

```js

Babel.registerPlugin('mangle', window.babelPluginMinifyMangleNames);

var output = Babel.transform(
  `function helloWorld() {
  	let bigVariableName = 'word';
  }`,
  {plugins: ['mangle']}
);

console.log(output)
```
