### ISSUE TITLE
Sandbox Exporting

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#6]
From sandboxes created by [ianjennings](https://github.com/ianjennings): babel/sandboxes#12  

Related to #9, #10, we should be able to publish the sandbox config to a github gist.

This probably just means rendering it in copy + pastable markdown somewhere.

**Comment by wlawt** [comment]
Related to #13, which will accomplish the majority of this issue.

**Comment by wlawt** [comment]
@ianjennings @srijonsaha would just providing the URL that #13 accomplishes be enough for this issue? Unless we want to make publishing to Github gist a priority?

**Comment by ianjennings** [comment]
Yeah I think so
