### ISSUE TITLE
Configure server for production

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#60]
- [x] The server must store all keys and secrets in a `.env` file
- [x] Keys and secrets must be removed from `.js` code
- [x] Sever should include an .env.example file
- [x] Sails must [lift in production mode](https://sailsjs.com/documentation/concepts/deployment)

Known Keys/Secrets:

- mongo
- s3

**Comment by mohammedsahl** [comment]
The config vars are tucked away in heroku currently. Anyone cloning the repo and setting up a local mongodb database need not worry about setting up a `.env` file unless they'd like to connect to the prod DB

`npm start` and `sails lift --prod`, the scripts needed to launch sails in prod` **will** throw an error

`sails lift [--port {PORT}]`, the script that connects to `localhost:{PORT}` should not throw, assuming mongo is setup correctly on `localhost`
