### ISSUE TITLE
Save Sandbox State

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#9]
From sandboxes created by [ianjennings](https://github.com/ianjennings): babel/sandboxes#9  

Sandbox should include some backend database (or otherwise) to persist state. This way, we hotlink another user to the sandbox as we set it up.

**Comment by ianjennings** [comment]
Related to #4

**Comment by ianjennings** [comment]
https://stackoverflow.com/questions/28314368/how-to-maintain-state-after-a-page-refresh-in-react-js

**Comment by ianjennings** [comment]
Look into Redux.

**Comment by ianjennings** [comment]
The babel AST explorer module has the ability to fork and persist, see here:
https://github.com/babel/website/pull/1933

**Comment by ianjennings** [comment]
Blocked by #25

**Comment by ianjennings** [comment]
@mohammedsahl this is good to close right?

**Comment by mohammedsahl** [comment]
@ianjennings yeah it's pretty much sorted apart from the S3 stuff
