### ISSUE TITLE
AST: Save state while switching tabs

### ISSUE THREAD

**Issue by wlawt** [MLH-Fellowship/babel-sandbox#91]
From #90 discussion

In the future, we would want to consider saving the state of the AST Explorer, so that if a user switches between JSON and AST Explorer (for whatever reason), they can just pick up where they left off.

**Comment by barronwei** [comment]
Preserving the settings of the AST visualization is straightforward, which will be fixed in #90, but keeping track of which part of the tree is toggled is going to be a different story.
