### ISSUE TITLE
Allow saving without custom plugin

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/babel-sandbox#96]
Right now we need to have a custom plugin before any of the server functions work. We shouldn't have to have a custom plugin on the client to save.

![image](https://user-images.githubusercontent.com/318295/90053935-c2d77680-dca0-11ea-816a-974b35d3f1ac.png)

@garrettluu says:

> figured it out! this bug ONLY happens when we have no custom plugin
> so it probably does something weird when trying to encode an empty string

See #93.

**Comment by garrettluu** [comment]
I believe this is an issue with how `REPLState` encodes and decodes empty strings; the backend should already be able to handle this. As you mentioned this morning, we can modify `REPLState` to store raw strings instead of base64 encoding and it will *probably* fix this issue
